Forrr new params consent
MagnumOpuses/af-connect-module pull request #49
Opened 2021-03-17 11:40 UTC by mobimation-gunnar

Implements module scope sharing of new parameters "jobRole" and "companyName".
af-connect-module scans files in module for occurrences of value assignments to
data-job_title
or
data-company_name 
in HTML elements of class "af-connect-module".

Such as :
``` 
<div id="af-connect-button" class="af-connect-module"
      data-job_title="Developer"
      data-company_name="Visma"
</div>
```
This enables use of these values in rendering.

2021-03-17 13:20 UTC, ixuz requested changes
Please update README.md to include descriptions for:
- data-company_name
- data-job_title

Also update the version number in README.md to `1.2.0-beta`

2021-03-18 19:46 UTC, mobimation-gunnar commented
Change done, will push update

2021-03-18 22:39 UTC, ixuz requested changes
Just a small change request, and then I think we're good to go.

2021-03-18 22:39 UTC, ixuz commented on README.md
> +| data-job_role     | The job role applied for   |
Slight change request `data-job_role`, should be `data-job_title`.

2021-03-18 22:41 UTC, mobimation-gunnar commented
Just det var fel.  Ok jag ändrar nu.

> On 18 Mar 2021, at 23:39, Anton Wiklund ***@***.***> wrote:
> 
> 
> @ixuz requested changes on this pull request.
> 
> Just a small change request, and then I think we're good to go.
> 
> In README.md <https://github.com/MagnumOpuses/af-connect-module/pull/49#discussion_r597288824>:
> 
> >  
> +| Custom property   | Description                |
> +| ----------------- | -------------------------- |
> +| data-purpose      | Phrase of intended purpose |
> +| data-company_name | Prospective employer       |
> +| data-job_role     | The job role applied for   |
> Slight change request data-job_role, should be data-job_title.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/MagnumOpuses/af-connect-module/pull/49#pullrequestreview-615929836>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AQGDMYIETQHTX5GKEP6FDBTTEJ6K3ANCNFSM4ZKNOPVA>.
>

2021-03-18 23:00 UTC, ixuz commented on README.md
> +| data-job_role     | The job role applied for   |
Resolved by https://github.com/MagnumOpuses/af-connect-module/pull/49/commits/49d001c12ab037b03d1ba682ea1130f5fee44c55

2021-03-18 23:00 UTC, ixuz approved these changes
Looks good, you may now squash and merge

2021-03-20 22:40 UTC, merged